name: Build

on:
  release:
    types: [created]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.x
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.0'
    - name: Prepare
      run: |
        sudo apt-get update 
        sudo apt-get install -y fakeroot rpm
        gem install fpm
    - name: Build
      run: |
        GOOS=linux GOARCH=s390x make cloudflared
        GOOS=linux GOARCH=s390x make cloudflared-deb
        GOOS=linux GOARCH=s390x make cloudflared-rpm
        cp cloudflared cloudflared-linux-s390x
        cp cloudflared_*.deb cloudfalred-linux-s390x.deb
        cp cloudflared-*.rpm cloudfalred-linux-s390x.rpm
        sha256sum cloudflared-linux-s390x cloudfalred-linux-s390x.deb cloudfalred-linux-s390x.rpm > sha256sums.txt
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          cloudflared-linux-s390x
          cloudfalred-linux-s390x.deb
          cloudfalred-linux-s390x.rpm
          sha256sums.txt
