name: Build

on:
  release:
    types: [created]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.x
    - name: Build
      run: |
        GOOS=linux GOARCH=s390x make cloudflared
        cp cloudflared cloudflared-linux-s390x
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          cloudflared-linux-s390x
